keylime/rust-keylime

.github/workflows/rust.yml

ci: Install tpm-tss2 dependencies

---

src/error.rs
src/handlers.rs
src/main.rs

Pretty-print error if main errors

---

.rustfmt.toml

Remove nightly rustfmt values

---

.github/workflows/rust.yml

Use tss2-dev instead of tss-dev

---

src/tpm.rs
tests/run.sh

Allow TCTI configuration via environment

---

docker/fedora/fedora.Dockerfile

Use the rust package instead of rustup

---

docker-compose.yml

Do not allow signing by swtpm

---

src/main.rs
src/quotes_handler.rs
src/tpm.rs

Add Quote functionality

---

src/cmd_exec.rs
src/crypto.rs
src/hash.rs
src/main.rs
src/registrar_agent.rs
src/revocation.rs
src/secure_mount.rs
src/tpm.rs

Some of the existing code is now failing clippy. This will let it pass again.

Fix new clippy lints

---

src/keys_handler.rs
src/main.rs

Remove verify stub as we are not using it

---

src/main.rs
src/quotes_handler.rs
src/registrar_agent.rs

Add more verbose logging to better match Python agent

---

src/main.rs

Otherwise, it throws "Exec format error (os error 8)" unless it is a
native binary.  Also simplified the logic to set executable bit of the
script.

Run payload script from a shell

---

src/quotes_handler.rs

Output mask info

---

Cargo.toml
src/tpm.rs

Fix clippy errors, update to newest TSS-ESAPI

---

CODEOWNERS
MAINTAINERS

codeowners also set, which allows for better branch protections
Resolves: #250
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Add Ueno as a maintainer and set codeowners

---

src/main.rs

Fixes: #247
Still a draft as I haven't checked every error case that we can ignore.

Retain the main loop running after payload execution

---

src/common.rs
src/keys_handler.rs
src/quotes_handler.rs

- Fixes `HMAC check failed for all U and V key combinations`
- Fixes `ERROR - agent did not provide public key`
Should fix #262 (#249 may need to be merged first, I will test tomorrow).

Fix bugs that occur after a delete and re-add from the tenant

---

src/keys_handler.rs

keys_handler: Add unit tests

---

.github/workflows/rust.yml
src/common.rs
tests/Dockerfile
tests/run.sh
tests/seccomp-profile.json

This might help address #204 by identifying the code not covered by the unit tests.

ci: Check unit test coverage with cargo tarpaulin

---

src/main.rs

The revocation service was starting before the payload
had been decrypted, and encountering an error since there
is no revocation cert before that time.
Fixes #270

Fix 0mq problem

---

src/revocation.rs

This should fix the panic in #297 (which is unrelated to code changes there).

Remove panic when running rev action

---

.github/CODEOWNERS
CODEOWNERS

Remove duplicate codeowners file

---

src/common.rs

Update to fix typo

---

Cargo.lock
Cargo.toml
src/main.rs

Add a --help message.

---

src/revocation.rs

Signed-off-by: greyspectrum <hello@greyspectrum.io>

Make clippy happy.

---

GNUmakefile
README.md
dist/systemd/system/keylime_agent.service

Also add a Makefile that wraps cargo and install commands.
Fixes: #271

Install systemd unit file

---

src/keys_handler.rs

The python keylime now sends the correct JSON Content-Type header.
Fixes: #306

keys_handler: Remove workaround for missing JSON Content-Type

---

src/main.rs

Use actix-web scopes to create a structured organization for the API.

main: Use scopes to organize API

---

MAINTAINERS

Add ansasaki as maintainer

---

Cargo.lock
Cargo.toml
src/crypto.rs
src/error.rs
src/errors_handler.rs
src/keys_handler.rs
src/main.rs
src/notifications_handler.rs
src/quotes_handler.rs
src/version_handler.rs

Update actix-web to 4, remove tokio 0.2 dependencies

---

src/common.rs
src/main.rs
src/registrar_agent.rs

Add support for 'mtls_cert_enabled' configuration option to disable mTLS on the agent.
Also add support for the 'enable_insecure_payload' to allow running payload scripts from untrusted peers.
Fixes: #349

Add option to disable mTLS

---

src/common.rs

Signed-off-by: Sergio Correia <scorreia@redhat.com>

Fix typo in config_get()

---

packit-ci.fmf

Add test /functional/measured-boot-swtpm-sanity to Packit CI plan

---

packit-ci.fmf

Resolves: https://github.com/keylime/rust-keylime/issues/396

Adjust CI test name according to keylime-tests PR#125

---

.github/dependabot.yml

This enables dependabot on the repository to automatically update dependencies

Add dependabot for automatic dependency updates

---

packit-ci.fmf

Set swtpm context which is later used for test filtering

---

src/main.rs

Fix display of mb measurement file path

---

src/crypto.rs
src/ima_entry.rs
src/keys_handler.rs
src/notifications_handler.rs
src/revocation.rs

Appease clippy

---

src/main.rs

Set the `tpm_ownerpassword` in the TPM context to be used for the Endorsement Hierarchy regardless of the value set in `ek_handle`.
This makes the `tpm_ownerpassword` set in the configuration file to be used to access the TPM when generating the EK handle.
Note: This doesn't change the TPM owner password, only provide it when creating a password session.

Use the tpm_ownerpassword when generating the EK

---

keylime-agent.conf

The comments in the configuration file didn't reflect the actual supported values and behavior.
Fixes #433 

Update comments in the configuration file

---

src/algorithms.rs
src/common.rs
src/secure_mount.rs

To increase testing coverage (`cargo tarpaulin`), I added a few tests to `src/common.rs`, `src/algorithms.rs`, `src/secure_mount.rs`. @lkatalin

Increase unit testing

---

packit-ci.fmf

Enabling more e2e tests in Packit CI

---

packit-ci.fmf

CI tests: Do not remove Fedora tag repository

---

Cargo.lock
keylime-agent/Cargo.toml
keylime-ima-emulator/Cargo.toml
keylime/Cargo.toml

Bump version to 0.2.0 as preparation for tag/release.

Bump version to 0.2.0

---

Cargo.lock
keylime-agent/Cargo.toml
keylime-ima-emulator/Cargo.toml
keylime/Cargo.toml
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec

Bump crates and RPM specfiles version to `0.2.1`

Bump version to 0.2.1

---

Cargo.lock
keylime-agent/Cargo.toml
keylime-ima-emulator/Cargo.toml
keylime/Cargo.toml
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec

Preparation for the new release v0.2.2

Bump version to 0.2.2

---

.github/workflows/container.yml

Update actions versions to avoid warnings.

Update container build workflow actions

---

.github/workflows/rust.yml

Use latest versions of checkout/upload-artifacts

---

README.md

Fixes: https://github.com/keylime/rust-keylime/issues/644

README: update dependencies for Debian and Ubuntu

---

packit-ci.fmf

Recently in keylime test suite were prepared new
tests for covering new functionality. Update packit plan to use them in CI.

Update packit plan with new tests

---

Cargo.lock
keylime-agent/Cargo.toml
keylime-ima-emulator/Cargo.toml
keylime/Cargo.toml
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec

Bump version to 0.2.3

---

Cargo.lock
Cargo.toml
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec

Bump version to 0.2.4

---

.github/workflows/container.yml
.github/workflows/rust.yml
.github/workflows/submit-HEAD-coverage.yaml
.github/workflows/submit-PR-coverage.yaml

Include newest Node20 versions for Github actions

---

.github/dependabot.yml

Extend dependabot configuration to monitor workflow action versions

dependabot: Extend to also monitor workflow actions

---

Cargo.lock
Cargo.toml

Update `reqwest` to version `0.12.7`

cargo: Bump reqwest to version 0.12.7

---

Cargo.lock
Cargo.toml

Bump the `tokio` crate to version `1.42.0`

cargo: Bump tokio crate to version 1.42.0

---

Cargo.lock
Cargo.toml
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec

Bump version to 0.2.7

---

keylime-agent/src/main.rs
keylime/src/registrar_client.rs
keylime/src/tpm.rs

See enhancement-1552: EK Certificate Chain support

Add support for ek certificate chain (stored in TPM NVRAM), resolves #1552

---

.gitignore
Cargo.lock
Cargo.toml
keylime-push-model-agent/Cargo.toml
keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/struct_filler.rs
keylime-push-model-agent/tests/evidence_supported_attestation_request.json
keylime-push-model-agent/tests/test-keylime-push-model-agent.rs

This prototype contains the basic structure
of the Push Model prototype. It allows
sending capabilities negotiation requests
to Verifier to check its current status
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

Push model prototype

---

keylime-push-model-agent/src/state_machine.rs

This patch modifies the agent's state machine to make the initial registration process more resilient by retrying indefinitely if it fails.
* New State (RegistrationFailed): A new state has been added to the state machine to specifically represent a failure during the registration phase. This separates registration failures, which are considered recoverable, from other critical errors that should terminate the agent.
* Updated register() Logic: When the register() function fails to connect to the registrar, it now transitions the machine to the new RegistrationFailed state instead of the generic Failed state.
* Infinite Retry Loop: The main run() loop in the state machine has been updated. When it detects the RegistrationFailed state, it logs the error and immediately transitions back to …

Retry registration forever in the state machine

---

keylime-push-model-agent/doc/fsm/mermaid_fsm.md

Include Mermaid FSM chart containing a description of both the states and transitions existing on the FSM

Add Mermaid FSM chart
