keylime/rust-keylime

.gitignore
src/common.rs
src/main.rs
src/tpm.rs
test_input.txt

I added a few test case to make sure the tpm function is working. Skipped quote function test, because I haven't figured out how to test this function. Also added some comments for each function to make clear what it does. Fixed some bug in tmp functions, now it is able to execute tpm command and getting the result back from tpm. 
But it won't pass the CI since CI doesn't contain tpm with it.

Test tpm function and bug fix

---

src/crypto.rs
src/main.rs

As the title suggests, this PR adds a binding for the PBKDF2-HMAC function in OpenSSL and configures it to match the [implementation in Python-Keylime](https://github.com/mit-ll/python-keylime/blob/2da18bd4814fb3c93d89175d2d5172b1167753c2/keylime/crypto.py#L83). An appropriate test is also added.
A few notes:
- This is also mentioned in the function documentation, but it bears repeating: The only reason this binding uses SHA-1 is because Python-Keylime uses it at the moment. PyCryptodome [defaults to SHA-1 as a PRF](https://pycryptodome.readthedocs.io/en/latest/src/protocol/kdf.html) if the `prf` parameter is not specified, and Python-Keylime does not provide that parameter in its KDF binding.
- The key the test compares against was generated from the Python-Keylime KDF binding using the …

Add key derivation function binding and appropriate tests

---

src/common.rs
src/main.rs
src/secure_mount.rs
src/tpm.rs

1. contains unsafe libc function

Add secure mount function

---

README.md
src/common.rs
src/main.rs
src/tpm.rs

Just getting my feet wet, so some typo fixes and a logging env example.

Add logging example and some readme fix ups

---

src/crypto.rs
src/secure_mount.rs

This is a **work-in-progress** pull request that implements bindings for two crypto functions necessary for the implementation of the Keylime Rust client (as per @leonjia0112). These also constitute a part of the crypto interface as specified in #20. Documentation for both functions is included inline.
Some notes to keep in mind:
- Per offline discussion with @leonjia0112 and @frozencemetery, we will be building our own error type to reconcile the different varieties of error the entire client will be dealing with, as documented in #42. For this reason, error handling should be considered incomplete for these bindings -- with the expectation that the functions should be revised to work with the new error type once it's been implemented.
- Tests do not yet exist for either function -- they …

Add OpenSSL bindings for RSA public key import and random RSA key generation

---

.travis.yml
.travis/nopanic.py
src/common.rs
src/main.rs
src/secure_mount.rs
src/tpm.rs

1. Removed all the unwraps for all the scripts under src/ directory except the testing suite.
2. Changes functions' return type to `Result<>` after removing the unwraps, which has better error handling.
3. Add a script to CI for catch a list of banned function that could possibly be panicking the thread and terminate the process. Both the shell script and the banned list are both `.travis/` directory.
The main change in main.rs is a loop scope is used to wrap around the request, once an error is encountered early exit the loop scope with the response that has the corresponding content regarding the error.
Now there should be now unwraps/panics in the repo and prevent further use of these panic function in this repo.

Removed all unwraps/panics for all code except testing

---

src/crypto.rs

This PR adds `KeylimeCryptoError`, a custom error type, to be used by all bindings in `crypto.rs`. This allows a uniform return type that handles a variety of different errors thrown by implementations of the crypto wrappers, without complex logic or loss of error information. More information can be found at the corresponding issue, #42.
Notes:
- `KeylimeCryptoError` is not included as a return type for existing functions at the moment. I intend to update the existing bindings with the new error type in a separate PR.
- Currently, `KeylimeCryptoError` preserves OpenSSL `ErrorStack` structs in their entirety by simply wrapping them. This allows further reference down the line if needed, though suggestions are welcome for simplification.
- Right now, `KeylimeCryptoError` can handle …

Add custom error type for OpenSSL bindings

---

src/crypto.rs

This PR is a follow-up to #49, implementing the new custom error as a return type for all existing crypto bindings. For most functions, the only change is a new return type; however, the `rsa_import_pubkey` function is refactored and overall cleaner as a result.
These changes are part of issue #42.
Tagging @frozencemetery, @leonjia0112, and @lukehinds for review.

Update existing crypto bindings to return custom KeylimeCryptoError

---

src/main.rs
src/secure_mount.rs
src/tpm.rs

Add support for tpm custom error type. This is aim on solving #40 for changing return type.
Implementation details:
1. Implement KeylimeTpmError enum has two contribution
- error generate from TPM command execution
- error generate from rust part of TPM interface
2. Implement From trait for Error:
- `serde_json::error::Error`
- `std::num::ParseIntError`    
- `std::string::FromUtf8Error`
- `std::io::Error`
- `std::time::SystemTimeError`    
3. Upate return type of `run()` function in a tuple and a custom error
`Result<(String, String), TpmExecError>`    
4. Support return type of other function in tpm.rs with `KeylimeTpmError`, which has benefit in code efficient and early return efficient

Add KeylimeTpmError support and change return type in tpm.rs

---

src/crypto.rs
src/main.rs

This PR implements a binding in `crypto.rs` for RSA decryption, necessary for work on the Rust client's POST handling logic. This addition also constitutes part of the crypto interface as specified in #20.
Tagging @frozencemetery @leonjia0112 for review.

Add crypto binding for OpenSSL RSA decryption

---

Cargo.toml
README.md
src/common.rs
src/main.rs

As per mailing list discussion [0] we decided to rename `node`
to `agent`.
The following pull request is open on python-keylime [1]
[0] https://keylime.groups.io/g/main/topic/node_agent/30833147
[1] keylime/python-keylime#97
resolves: #58

Rename `node` to `agent`.

---

Cargo.toml
keylime.conf
src/common.rs
src/main.rs
src/secure_mount.rs

This pull request allows the agent to make use of the existing
INI config format used in the python variation of keylime.conf
It also allows declaration of an individual config file for each
function call. This will allow future use of more config files
(should we care to have them) such as `database.ini` or
`myplugin.ini`
I selected `rust-ini` crate as it is an active and maintainted
project generally considered stable
Resolves: #27

Implements Config Parser

---

README.md

Updated old URLs pointing to the mit-keylime repository and
remove references on TPM1 emulator / stack which are no longer
planned to be supported (only TPM 2.0)
Recommend that when we are in the position (working rust agent) we
can update with the details needed to fully install and set up

Update README.md to remove TPM1 ref  and update URL

---

src/cmd_exec.rs
src/keylime_error.rs
src/main.rs
src/secure_mount.rs
src/tpm.rs

This change ports the `run` function from `tpm.rs` into its own
file / module `cmd_exec.rs` - primary reason for this is that non
tpm functions also call on the `run` function, so its not
exclusive to tpm operations (for example secure_mount uses run)
For `KeylimeTpmError` - this has been ported into a module
`keylime_error`, so that we can group all errors into a single
module, as it makes sense that we will eventually have more
error types and have them neatly self contained in single module
Resolves: #81

Port `run` and `KeylimeTpmError` to unique modules

---

src/secure_mount.rs

Currently the code splits the mount command line returns
incorrectly. This results in a non match which means a new
mount is created everytime, instead of using an existing mount.
This results in many mounts being present on the system, every
time the agent is restarted.
This is due to the split element being a back slash `\` whereas
it should be a whitespace `' '`
There is also no feedback provided to the user when an existing
mount is used. This information should be provided to the user.
Resolves: #83

Fix line split in secure mount and notify

---

src/hash.rs
src/main.rs

Not sure if this is truly needed or not, but just in case ....
`is_accepted` left out as it's more of a generic function.
May help with #66
See: https://github.com/keylime/keylime/blob/master/keylime/tpm/tpm_abstract.py#L47

hash: Port HashAlgorithms

---

keylime.conf
src/main.rs

We may need to think of better ways of syncing the conf between
both projects. For now I have moved the file over in its entirety
as we will require integration tests and so forth (so keys around
the verifier and register will be used there).

Update keylime.conf to latest version

---

Cargo.lock
Cargo.toml
src/error.rs
src/handlers.rs
src/main.rs

This change enables us to run multiple async operations by using
`futures::try_join`
With this we will be able to run both the web service and the
revocation service, whereas <function>.await will block futher
code execution

Implements try_join for running multiple async

---

docker/fedora/fedora.Dockerfile

Running a container from this image with a bind mount to the host copy of the rust-keylime repo creates a dev environment that will work properly (no missing libraries, env vars, etc.).

Add Dockerfile to create Fedora dev environment

---

Cargo.lock
Cargo.toml
src/main.rs
src/tpm.rs

This PR makes us use the Git copy of tss-esapi for now, while we are still actively adding features there.
It also adds the TPM vendor check from #113.

Use git tss-esapi and add tpm vendor check

---

tests/nopanic.ci

Calls to nopanic / unwrap can be allowed by using #[allow_ci]

Allow nominator for CI checks on  banned calls

---

src/cmd_exec.rs
src/crypto.rs
tests/nopanic.ci

This allows Rust to ignore it, but our CI tests to detect it.
~~Edit: The failures are related to the `unwraps()` that this tests for and which are fixed in #144 .~~

Make #[allow_ci] a comment

---

.github/workflows/keylime-bot.yml

Roughly equivalent to https://github.com/keylime/enhancements/pull/35.
Once merged, pull requests will:
- automatically have reviewers requested (currently pulls from Github's suggested reviewers and the `rust-team` team)
- have their assignees updated based on who is most responsible at any given time
Since bot setup was already done for `enhancements`, this should be good to go as is.

Enable PR assignment automation from actions-automation

---

Cargo.lock
src/tpm.rs

If this needs more functionality, different return types, etc., please let me know.

Add create_ek() to tpm.rs

---

Cargo.lock
Cargo.toml
src/tpm.rs

This version of `tss-esapi` includes everything that rust-keylime will need.

Bump to tss-esapi-4.0.10-alpha.2

---

src/error.rs
src/tpm.rs

Resolves #115 
I changed the name ~~to `get_ek()` because that seems like what it does (rather than "use" the ek)~~.
Please let me know if I should make changes or if this isn't the right way to generate the key handle.

Implement get_ek() function

---

Cargo.lock
Cargo.toml
src/crypto.rs
src/error.rs

This makes our Error use thiserror to derive the std::error::Error
implementation.
This makes it easier to implement a useful Display for the errors.

Some error improvements

---

src/main.rs
src/quotes_handler.rs

The following code replicates python agent code:
https://github.com/keylime/keylime/blob/d987c71dd878492ac2b59eca781009fe270d219a/keylime/keylime_agent.py#L95-L114
This is more or a less at the point that we can call the tpm for quote.
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Basic quote handlers

---

Cargo.lock
Cargo.toml
src/crypto.rs
src/error.rs
src/main.rs
src/revocation.rs
tests/Dockerfile

Adds:
- Cargo: Add zmq and bump versions
- crypto: `rsa_verify` function
- main: `run_revocation_service` implementation
- tests/Dockerfile: Updated dep
Note: [Callback](https://github.com/keylime/keylime/blob/561a5b065a206f9873c9892754638fba0c0d7acc/keylime/keylime_agent.py#L596) is not implemented here.
See: https://github.com/keylime/rust-keylime/issues/92

Implement revocation service from Python code

---

Cargo.lock
Cargo.toml
src/error.rs
src/revocation.rs
tests/Dockerfile
tests/unzipped/action_list
tests/unzipped/rev_script1.py
tests/unzipped/rev_script2.py
tests/unzipped/test.json

This code runs those revocation scripts which were sent by the tenant and can be accessed from the secure mount point post-attestation.
I've decided not to check whether the revocation scripts begin with `local_action`, since they are all listed in `action_list` anyhow. But if someone has a reason that they should be marked that way, I can add this check back again.
I had a few other thoughts and questions inline marked with `TODO` and would love some suggestions on those points. The most important being: If these scripts don't run for whatever reason (ex. the Python version was too old), is that detected in some other part of the code? It seems like we would want a guarantee that a node can't continue to be in the cluster if it doesn't run the scripts, since it could still be in …

Call revocation actions

---

.rustfmt.toml
docker/fedora/wait.sh
license-header.tpl
src/cmd_exec.rs
src/common.rs
src/crypto.rs
src/error.rs
src/hash.rs
src/keys_handler.rs
src/main.rs
src/quotes_handler.rs
src/revocation.rs
src/secure_mount.rs
src/tpm.rs
tests/nopanic.ci
tests/run.sh
tests/unzipped/rev_script1.py
tests/unzipped/rev_script2.py

- Add ASLv2 SPDX header to source files
- Add `license-header.tpl`
- Add commented out config for `rustfmt` to check for license headers in the future
Resolves #111

Apache license header to source files

---

src/common.rs
src/main.rs
src/revocation.rs
src/secure_mount.rs
src/tpm.rs

`KEYLIME_CONFIG` can be set to override the default config file location.
*Note*:
I think we should eventually rework the configuration system so that we load the configuration once and then reload when we receive the proper signal. My reasoning is that the current set up means that if the file changes while the agent is running then the result could be old and new variables in use based on when they have been read. I've started to make structs for the keylime config. If folks agree I'll slowly but surely chip away at that no matter if this merges or not :smile:

Override config location with environment variable

---

docker/fedora/keylime_rust.Dockerfile
src/cmd_exec.rs
src/error.rs
src/revocation.rs
src/secure_mount.rs

These all relate to running the `keylime_agent`, `keylime-verifier`, and `keylime-registrar` with `docker-compose`, but some of the fixes are also generally applicable. Backstory: I am trying to make sure the components can work together before writing the 3-party key protocol. These are changes I made while fixing some bugs or trying to understand them.
~~I am still debugging some errors, so there are probably a few more commits to be added. EDIT: But these could go in an immediate future PR as well.~~
~~Currently:
`ERROR keylime_agent::revocation   > Path for the 0mq socket: /tmp/secure/unzipped/RevocationNotifier-cert.crt doesn't exist`~~

Small fixes relating to Keylime components working together

---

docker-compose.yml
docker/fedora/keylime_py.Dockerfile
src/cmd_exec.rs
src/common.rs
src/main.rs
src/registrar_agent.rs
src/secure_mount.rs

In this PR:
- Update to send IPs and ports and env vars (resort to keylime.conf if vars are not present)
- Add `efivar-devel` to `keylime_py` dockerfile
- Add `network_mode: host` to `keylime_agent` in docker-compose file, update port bindings, use IP `0.0.0.0`
Fixes #167

Fix communication errors between agent and registrar

---

Cargo.toml
docker-compose.yml
src/common.rs
src/error.rs
src/main.rs
src/revocation.rs
src/secure_mount.rs

This PR:
- fixes an error in the Keylime agent saying it is unable to mount the tmpfs by adding a "testing" feature
- adds more verbose error output for revocation and TPM-related errors
- adds logging output when agent activation and registration succeed
- removes port bindings for the agent (this was causing another error)

Fix secure mount error and add more verbose TPM error output

---

src/crypto.rs
src/revocation.rs

Ensure we no longer need to clone the RSA key every time we want to
validate anything.

Pass a PKeyRef to asym_verify

---

.gitignore
Cargo.toml
src/main.rs
src/tpm.rs

Rebase our use of tss-esapi to the 5.0 version, to ensure long time
success.

Rebase on tss-esapi 5.0

---

src/crypto.rs
src/revocation.rs

Following on #181, use the openssl crate's PKey type instead of the inner
RSA type. Also, add additional key-related helper functions. (These make the future identity quote code less messy.)

Use PKeys consistently

---

src/tpm.rs

These are useful for the future identity quote code.

Add more TPM helper functions

---

src/tpm.rs

- activate_credential() must flush context
- get_hash_alg() should not capitalize sha256
- pubkey_to_tpm_digest() should return digest of hash of key, not of key
Co-authored-by: Patrick Uiterwijk <patrick@puiterwijk.org>

Small fixes in TPM functions

---

src/tpm.rs

Fixes #192 
Also fixes #194 with many thanks to @puiterwijk for debugging
**### Please start with reviewing this PR before the others!**

Add marshaling functions for TPM structs

---

src/error.rs
src/quotes_handler.rs

This should pass CI when rebased on #195 
Thoughts: the JsonWrapper and KeylimeQuote variations are completely based on the Python interface, so they could possibly go in their own interface module. On the other hand, there isn't much code here so it may not be necessary to separate it that way. Opinions welcome.
Also: will we ever need to use the vmask? From what I understand, it is only necessary when tying a vtpm value to a hardware tpm value, which isn't used anymore in the Python codebase? But I could be wrong here.

Add handling for Identity and Integrity quotes

---

README.md

I was hitting build failures without these, so just adding
a note
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Add dependency for libzmq3-dev / zeromq-devel

---

src/main.rs
src/registrar_agent.rs
src/tpm.rs

According to the spec (4.5.2), it is not mandatory that an EK
certificate is pre-provisioned in NVRAM; actually some TPM chips do
not have it, e.g., AMD fTPM, and the Python registrar tolerates
"ekcert: null".

Do not fail if EK cert is not present in TPM NV

---

src/quotes_handler.rs

This is outdated and no longer required.

Drop references to vmask

---

src/crypto.rs
src/revocation.rs

The revocation cert must be read in as X509 before it can be converted
to a PKey<Public> pubkey.
Fixes #228

Fix bug in revocation service

---

src/quotes_handler.rs

This keeps the CV from resending the V key each time it polls for
an integrity quote.
Fixes #211

Do not resend pubkey to CV after attestation

---

Cargo.toml
src/error.rs
src/tpm.rs

This change adds a check to make sure digests returned in the Quote match the PCR values retrieved from `pcr_read`. There can be a mismatch here due to a race condition inherent to TPM2.0. See section `17.6.2` in TCG's [TPM spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf) for more on this race condition.
There were also some ESAPI bugs related to the ordering of data in `PcrSelectionList` and `PcrData`, affecting our results. Therefore the code is temporarily pinned to a branch of the ESAPI until @puiterwijk 's ESAPI [bug fixes](https://github.com/parallaxsecond/rust-tss-esapi/pull/236) are merged.
Fixes #210

Fix for race condition bug

---

src/common.rs
src/keys_handler.rs
src/main.rs
src/quotes_handler.rs

The key types seem like a good idea, especially if we start using vectors of U and V keys, which become cumbersome to read everywhere. I'm not completely convinced about making the U and V keys into sets as it adds a bit of complexity and seems like not the best way to mitigate attacks, but this would at least get the Rust agent to do what the Python agent is doing. Fixes #209 fixes #237

Accept sets of U and V keys; use new Key types

---

README.md

Rust complains that it can't find libarchive but what it really needs
are the header files.

libarchive-devel is needed to build on Fedora

---

src/common.rs
src/main.rs
src/registrar_agent.rs

This is in preparation for the versioned-apis feature to land in keylime main.

Add "v1.0" prefix to agent APIs

---

Cargo.lock
Cargo.toml
src/common.rs
src/error.rs
src/tpm.rs

This makes it possible to build this crate with the Rust toolchain in
Fedora, so the keylime_agent binary can be packaged as an RPM.
The commit comprises the following:
- Use tss-esapi 6.1.1 from crates.io
- Bump rust-ini dependency to 0.17
- Bump pretty_env_logger dependency to 0.4
- Bump hex dependency to 0.4
- Move wiremock to dev-dependencies
Fixes: #239

build: Adjust package dependencies to compile in Fedora

---

src/error.rs
src/keys_handler.rs

It is generally recommended that HMAC verification should be done
using a constant-time primitive so it does not involve timing side
channel.  This uses openssl::memcmp as suggested in the crate
documentation:
https://docs.rs/openssl/0.10.36/openssl/sign/index.html#examples

keys_handler: verify HMAC in constant-time

---

Cargo.lock
Cargo.toml
src/ima_emulator.rs
src/revocation.rs
src/tpm.rs

Fixes #234 
At long last, we have a fix for the > 8 PCR read bug. This bug fix was made in the `rust-tss-esapi` and this PR brings our code up to date with theirs.
I think the goal will be using `rust-tss-esapi` realease `7.0.0` as our dependency because this will be the release that incorporates the PCR read bug fix. There are more changes coming in for that release so we will probably have to make further changes also. Until then the dependency is on the `rust-tss-esapi` repo so that we can keep up.

Code refactor to use updated tss-esapi

---

src/tpm.rs

IMA now works with all hash algorithms: https://github.com/keylime/keylime/pull/803
The agent seems to currently use always sha256, but this will be changed in a separate PR.

tpm: remove special handling for PCR10

---

src/common.rs
src/main.rs
src/quotes_handler.rs
src/registrar_agent.rs
src/serialization.rs
src/tpm.rs

The agent now also sends the UEFI eventlog for measured boot attestation.
I've also moved our serialization functions to a new module because it can be shared between quotes handler and the registration process.

quotes_handler: send the TPM2 UEFI eventlog if PCR0 is in mask

---

src/common.rs
src/keys_handler.rs
src/main.rs
src/revocation.rs
src/secure_mount.rs

This moves the entire used configuration into a struct called `KeylimeConfig` and makes the all the `config_get` functions private.
The goal of this change is to load the configuration only once during startup and to keep most of the functions behaviour independent from global state. I don't think that partial config reload during execution makes sense, because in most cases a change would require a complete restart of the agent (generating new AK with different algorithm for example).
The config struct is currently passed by reference where possible. It might be required to use an Arc instead if we allow it to be shared between threads.
We should discuss before this gets merged, when functions take the config struct and when they are just taking single arguments for values that are in …

move global configuration into one single struct

---

src/common.rs
src/revocation.rs

The certificate to be used can be set through the ``revocation_cert`` entry in ``cloud_agent`` section of the configuration file.
Following the python agent behavior:
- If the ``revocation_cert`` is set as ``default``, use the default certificate path
- If the ``revocation_cert`` is an absolute path, use the provided path to obtain the certificate
- If the ``revocation_cert`` is a relative path, expand the path from the ``WORK_DIR``
- If the ``revocation_cert`` is empty, return an error
Fixes: #300

Use revocation certificate according to configuration

---

Cargo.lock
Cargo.toml
src/tpm.rs

This updates the version requirements for the following crates, to
catch up with the set of packaged dependencies in Fedora:
- base64: 0.12 → 0.13
- compress-tools: 0.11.2 → 0.12
- static_assertions: 0.2.3 → 1

Bump versions of some dependencies

---

src/common.rs
src/crypto.rs
src/error.rs
src/main.rs
src/revocation.rs
src/secure_mount.rs

We previously used different types (&str, String, etc) to represent
filesystem paths and converted between them and Path back and forth.
This standardizes those to use Path and PathBuf consistently.

Use Path and PathBuf consistently to represent paths

---

Cargo.lock
Cargo.toml
src/ima_emulator.rs
src/tpm.rs

The stable release is expected soon, but let's bump first to the beta
to catch any errors.

Bump tss-esapi crate to 7.0.0-beta.1

---

keylime.conf
src/common.rs
src/main.rs
src/notifications_handler.rs
src/quotes_handler.rs
src/revocation.rs
src/secure_mount.rs

The working directory can be set via the KEYLIME_DIR environment
variable or keylime_dir configuration option.
When the working directory is set, the expected location for the
certificates and secure mount are also modified and are relative to the
location set via KEYLIME_DIR.
The DEFAULT_CA_PATH is now relative to the working directory.
Consolidate the conditional change of the secure mount location when
testing to a single location.
Modify the revocation tests to use a temporary directory as the working
directory.
Fixes: #333

Set working directory via KEYLIME_DIR env variable

---

src/common.rs

It was updated to 2.1 based on Keylime enhancement #53
(agent-local revocation), but this broke communication
with the Python components. We have [decided](https://github.com/keylime/keylime/pull/907) that the
Rust agent should not have its own API version, but
rather follow API versioning from the Python components.

Revert API version to 2.0

---

keylime.conf
src/main.rs
src/revocation.rs

The revocation actions names are no longer required to start with
'local_action_'.
This implements the enhancement amendment added via:
https://github.com/keylime/enhancements/pull/63

Remove revocation actions naming restriction

---

src/main.rs

Follow python agent implementation and ignore `payload_script` if it is
set in configuration but it is not provided in the payload.
Fixes: #336

main: Do not error if payload_script is not found

---

src/main.rs
src/version_handler.rs

Introduce a handler for GET requests to /version REST endpoint which
returns the latest supported API version.
Fixes: #313

version_handler: Introduce /version REST endpoint (#313)

---

src/ima.rs
src/main.rs
src/quotes_handler.rs

Rebase the changes proposed in #277 on top of current master.
Small changes were added:
- Applied changes suggested by `cargo fmt` and `cargo clippy`
- Avoid using `unwrap()`, `panic!()`, and cloning when possible
- Move added unit test to a module

Add support for iterative attestation

---

src/common.rs
src/keys_handler.rs
src/notifications_handler.rs
src/quotes_handler.rs
src/version_handler.rs

Use a generic JSON wrapper implementation for HTTP responses instead of implementing a specific wrapper for each JSON content.

Use shared JSON wrapper for HTTP responses

---

src/keys_handler.rs

The test_u_or_v_key_long() was using a 128 bits long key instead of 256
bits.

keys_handler: Fix test for 256-bits keys

---

src/keys_handler.rs
src/main.rs

Add the handler to the agent for GET requests to '/keys/verify' endpoint.
The handler expects the 'challenge' parameter as 20 alphanumeric characters string and responds with a JSON structure containing the resulting hex-encoded HMAC-SHA384 calculated using the symmetric key derived from U and V keys and the challenge as the input.

Add API to verify derived key

---

src/ima.rs
src/quotes_handler.rs
src/tpm.rs

Unify `KeylimeIdQuote`, `KeylimeIntegrityQuotePreAttestation`, and `KeylimeIntegrityQuotePostAttestation` structures into the single `KeylimeQuote` structure, using `Option` for optional fields.

Simplify integrity quotes structures

---

src/common.rs
src/keys_handler.rs
src/quotes_handler.rs

The response for requests should always be wrapped in the JSON structure, including in error cases.
Without this, the rust agent returns malformed responses on error cases, advertising `content-type: application/json` on the header, but sending plaintext on the body, which caused JSON parsing errors.
This was found during implementation of https://github.com/keylime/keylime/pull/947.

Use JSON wrapper on error responses

---

src/common.rs
src/keys_handler.rs
src/quotes_handler.rs
src/version_handler.rs

Rename `JsonWrapper::new` as `JsonWrapper::success` to clarify the purpose which is to wrap the content with the JSON structure with success status code.
Also replace `JsonWrapper::bad_request` with `JsonWrapper::error` which receives the error status code as a parameter, allowing wrapping the error message with different error status codes.

Rename JSON wrapper methods

---

src/common.rs
src/errors_handler.rs
src/keys_handler.rs
src/main.rs
src/quotes_handler.rs

Generate log messages equivalent to those generated by the python agent.
Improve error handling and logging for requests.
Fixes #213

Improve logging and error handling

---

src/quotes_handler.rs

The measured boot log is expected to be a base 64 encoded string.
Fixes: #367

quotes_handler: Fix measured boot list encoding

---

GNUmakefile
dist/systemd/system/keylime_agent.service
dist/systemd/system/var-lib-keylime-secure.mount
src/common.rs
src/error.rs
src/ima.rs
src/keys_handler.rs
src/main.rs
src/notifications_handler.rs
src/permissions.rs
src/quotes_handler.rs
src/revocation.rs
src/secure_mount.rs

After finishing operations that require privileges, drop the privileges to run as a normal user.
This adds support to the `run_as` configuration option to select the `user:group` under which the keylime agent will run.
This also rewrites `check_mount()` to use the information from `/proc/self/mountinfo` instead of the mount output file to check if `secure` is mounted. The implementation was based on python agent.
Fixes: #343, #317, #344

Drop privileges after startup

---

src/main.rs

When mTLS is disabled, the CA certificate is not necessary and the agent
should not fail to start when it is not available.
Fixes: #378

main: Do not try to load CA cert if mTLS is disabled

---

Cargo.toml
src/main.rs
src/revocation.rs
tests/actions/local_action_stand_alone.py
tests/unzipped/action_list

Add the 'legacy-python-actions' feature, enabled by default, to control
whether the agent supports python revocation actions loaded as modules.
Note that this is the only kind of revocation actions script supported
by the python agent implementation, which means that removing this
feature will make existing revocation actions unusable.
Disabling the 'legacy-python-actions' feature will not disable the
support for running stand-alone python revocation action scripts, i.e.
executable python scripts can be used as a revocation actions scripts,
as well as any other executable.
Fixes: #368

Make support for legacy python revocation actions optional

---

src/keys_handler.rs
src/quotes_handler.rs
src/registrar_agent.rs

Add the `#[serde(skip_serializing_if = "Option::is_none")]` annotation to
all optional fields serialized using `serde`.  This makes `serde` to skip
serializing optional fields when the value is `None`.
Fixes: #380

Skip serialization of optional fields

---

src/quotes_handler.rs

Rewind the file before reading its content.
Fixes: #383 

quotes_handler: Rewind measured boot log file

---

Cargo.lock
Cargo.toml
src/common.rs
src/error.rs
src/main.rs
src/tpm.rs

The tss-esapi crate provides now the conversion functions for Public to a more standard key format.
This PR first updates to the newest tss-esapi version and then implements the hash_ek option for UUID creation.

Add support for hash_ek UUID creation

---

Cargo.toml

To reduce the risk of being compiled with an outdated vulnerable
version, update the tokio minimum required version.
This is to avoid tokio < 1.13.1, which is affected by:
https://rustsec.org/advisories/RUSTSEC-2021-0124.html
This solves the possible vulnerability listed in:
https://deps.rs/repo/github/keylime/rust-keylime

Update tokio minimum version

---

.github/dependabot.yml

By default dependabot creates PRs that update each dependency to the
latest possible version.  That would be problematic if we use crates
packaged in distributions such as Fedora.  This forces the
"lockfile-only" strategy to only allow minor updates:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

.github/dependabot.yml: prevent updates that require manifest change

---

packit-ci.fmf

Update fmf plans for enabling run test with simple
IMA policy. With simple IMA policy will be run one
test. Then update IMA policy to signing policy and
run all tests.

Update fmf plans to run test with IMA policy

---

src/tpm.rs

Add serialization and deserialization functions for the data in quotes
to avoid endianness issues when the arch is big-endian.
The added serialization and deserialization functions will convert the
data endianness as necessary.
Note: the official marshalling and unmarshalling functions cannot be
used directly because the tpm2-tools uses a custom format.
Fixes: #407

tpm: Add serialization functions for structures in quotes

---

GNUmakefile

Previously, at "make install" the programs are always rebuilt with
cargo, even if they already exist as a result of prior invocation of
"make", which causes a problem if cargo is installed locally for the
user with rustup.  This adds explicit prerequisites to the build
target to avoid that.
Fixes: #420

GNUmakefile: Make target dependencies explicit

---

src/common.rs

This fixes #390 and reduces the number of times the configuration file is loaded during startup. To achieve this, the opened Ini object is passed around rather than being opened with each call to config_get or config_get_env.
@lkatalin

Load config file less at startup

---

src/keys_handler.rs

The MutexGuard is not async aware, meaning the mutexes should be
unlocked before any await call.  This change uses scopes to drop the
locked mutexes before calling await.

keys_handler: Use scopes to drop mutexes before await

---

src/common.rs
src/main.rs

Signed-off-by: greyspectrum <hello@greyspectrum.io>
Closes #408

Handle whitespace in keylime.conf

---

.gitleaks.toml

Add GitLeaks configuration to ignore RSA key used for testing

---

packit-ci.fmf
src/common.rs
src/main.rs
src/tpm.rs

Previously it always generated new EK handle even if the "ek_handle"
option is set to use the existing key.

tpm: Respect ek_handle from config

---

keylime.conf

The compatibility part has been already addressed in
https://github.com/keylime/rust-keylime/pull/320
but keylime.conf itself hasn't been updated yet.

Fix typo in listen_notifications option in keylime.conf

---

src/common.rs

Add more helpful error when config file is not found

---

packit-ci.fmf

These context are to be used for proper test case filtering.
Current upstream plan installs modified Rust agent which
reads faked measured boot log, enabling measured boot testing
on systems with runtime swtpm emulation.
Distribution RPMs are not modified this way and undefined context
faked_measured_boot_log gives as a way how to avoid running measured
boot test that would fail.

Add agent and faked_measured_boot_log tests context

---

.github/workflows/rust.yml

Added `cargo audit` to the rust CI workflow. 
There are other options for automatic security analysis, so please let me know your thoughts!
Another option would be to use the [rust audit-check action](https://github.com/marketplace/actions/rust-audit-check) on GitHub. 
Also, this [dependency reviewer action](https://github.com/actions/dependency-review-action) could be used. 
This is related to #94 
@lkatalin

Add cargo audit to test workflow

---

keylime-agent.conf

The option has been introduced in
https://github.com/keylime/rust-keylime/pull/426
but keylime.conf has not been updated with it.

Add tpm_ownerpassword option to keylime.conf

---

Cargo.lock
Cargo.toml

Generate the tss-esapi bindings during compilation time.  This will extend the ammount of supported architectures.
Signed-off-by: Alberto Planas <aplanas@suse.com>

Cargo.toml: tss-esapi bindings

---

README.md

This removes the disclaimer that the rust agent should not used in production and replaces it with that this agent is now the official one.

README: mark Rust agent as the offical one, fix cargo run command

---

Cargo.lock
Cargo.toml
src/config.rs

These are not direct depedencies anymore with the introduction of the 'config' crate.

Cargo: Drop unused dependencies rust-ini and toml

---

src/main.rs

The main function also had a local variable called uuid. This variable
contained either the provided uuid or when "hash_ek" was set the sha256 hash
of the EK. We never updated the KeylimeConfig struct which caused a mismatch
between uuids used in the program. Instead we now mutate the KeylimeConfig
when "hash_ek" is set to the correct value.

main: only read uuid from KeylimeConfig

---

README.md
debian/keylime_agent.postinst
keylime-agent/Cargo.toml

This adds the required files and options to build the agent using cargo deb.

add support for cargo deb

---

packit-ci.fmf

This service running on background can consume a lot of memory, resulting in OOM killer interrupting tests.

Disable dnf-makecache.service to save RAM

---

keylime-agent/src/main.rs

In 1.66 / 1.66.1 const_err is already a hard error, and was enabled as such as long ago. New compilers will complain in case that this is still used:
warning: lint `const_err` has been removed: converted into hard error
More info:
https://github.com/rust-lang/rust/issues/71800

keylime-agent: remove const_err deny

---

keylime-agent/src/common.rs
keylime-agent/src/config.rs
keylime-agent/src/crypto.rs
keylime-agent/src/error.rs
keylime-agent/src/errors_handler.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/notifications_handler.rs
keylime-agent/src/permissions.rs
keylime-agent/src/quotes_handler.rs
keylime-agent/src/registrar_agent.rs
keylime-agent/src/revocation.rs
keylime-agent/src/secure_mount.rs
keylime-agent/src/serialization.rs
keylime/src/algorithms.rs
keylime/src/ima/entry.rs
keylime/src/tpm.rs

This allows for setups with intermediate CAs.

crypto, mTLS: allow certificate chain for trusted_client_ca

---

keylime-agent.conf
keylime-agent/src/config.rs

For python agent was openstack option already removed, and in rust agent is stil placeholder for this option, but won't be used. [1] Remove related unit test and notes about openstack method in agent conf. Can be confusing for user to see openstack option as method for obtaining uuid.
[1] https://github.com/keylime/keylime/commit/c9f7906a0d254a4fceef8e9b0c612b378c27d6e4

Remove unused option "openstack" for obtaining uuid

---

keylime-agent/src/common.rs
keylime-agent/src/error.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/notifications_handler.rs
keylime-agent/src/payloads.rs
keylime-agent/src/revocation.rs

Use messages for synchronization instead of mutexes and condvar.  Add
separate workers for keys, payload, and revocation execution, as well as
a worker to handle the revocations coming from ZeroMQ channel.
The workers  hold the state locally instead of storing all data in server
context (QuoteData).
The keys worker holds the received U and K keys and is responsible for
combining them to obtain K.  It also provides the K key when requested
by the /keys/verify endpoint to prove that the resulting K is correct.
When the U and V keys combination is successful (the HMAC verification
is successful), the keys worker wakes the payloads worker sending the
obtained K key and the encrypted payload.
The payloads worker is responsible for decrypting and running the
payload sent by the keys worker. …

Refactor async code synchronization

---

packit-ci.fmf

e2e tests: Fix test name

---

keylime-agent.conf
keylime-agent/src/common.rs
keylime-agent/src/config.rs
keylime-agent/src/crypto.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/payloads.rs
keylime-agent/src/registrar_agent.rs
keylime/src/tpm.rs

Read the configuration options set via environment variables separately
to initialize an EnvConfig structure and use this structure as a
Source to override the values of the KeylimeConfig obtained from the
configuration files.
For this, change the prefix for the environment variables to
KEYLIME_AGENT with the 'prefix_separator' as '_', and 'separator' as
'.'.
Then the configuration options obtained from the environment variables
are used to initialize an EnvConfig structure, which does not contain
sub-structures.
The EnvConfig structure is a duplicate of AgentConfig structure, but
contains Option<T> for all configuration options, allowing values to not
be set via environment variables.
The remaining optional fields in AgentConfig were replaced to be
required (not Option<T>).
Note that the …

config: Fix overriding options with env vars

---

keylime-agent.conf
keylime-agent/Cargo.toml
keylime-agent/src/config.rs
keylime-agent/src/main.rs

The features are disabled by default and will be removed on next major
release.
This changes the default value of the 'enable_revocation_notifications'
to false. 
Note:  The default value used by the python configuration upgrade script needs to be updated accordingly.

Deprecate `with-zmq` and `legacy-python-actions` features

---

.packit.yaml

With the updated tpm2-tss and rust-tss-esapi, it is possible to build the agent on Fedora Rawhide again.

packit: Re-enable tests on Fedora Rawhide

---

packit-ci.fmf

Remove workaround where `tpm2-tss` is downgraded.

packit: Remove workaround for Fedora BZ#2158598

---

keylime-agent/src/config.rs

When running tests on machines where `/var/lib/keylime` does not exist (e.g. build machines where keylime is not installed), the tests would fail on the check if keylime_dir exists.

config: Skip validation of keylime_dir during tests

---

.github/workflows/submit-HEAD-coverage.yaml
.github/workflows/submit-PR-coverage.yaml
codecov.yml
packit-ci.fmf
scripts/download_packit_coverage.sh

Implement github action which gather code coverage of PR against master branch. And after merge it gather code coverage again. Add helper script which gather code coverage from testing farm. And update e2e plan where run tasks for measuring code coverage.

Coverage for rust agent as github action

---

codecov.yml

This is misconfiguration from keylime project,
in codecov yaml where are uploaded 3 coverage
files, but for rust keylime is uploading only
2 coverage files.

Change number of required uploaded files

---

Cargo.lock
keylime-agent/Cargo.toml

This is to fix the possible vulnerability reported by cargo audit on `remove_dir_all`.
The new version of tempfile dropped the dependency on `remove_dir_all`

Cargo: Update tempfile to 3.4.0 version

---

packit-ci.fmf
scripts/download_packit_coverage.sh

Fix typo in name of test for generating coverage

---

.packit.yaml
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec
rpm/fedora/rust-keylime-metadata.patch

Build Fedora packages on Copr when new commits are pushed to master branch.
This includes a specfile similar to one used downstream on Fedora, and a patch to make the build to use the dependencies version that are available on Fedora.
EDIT: For CentOS Stream I need to do some extra steps as it needs all dependencies to be vendored.

Build Fedora packages on Copr using packit

---

.packit.yaml
keylime-agent/src/common.rs
keylime-agent/src/main.rs
rpm/README.md
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec
rpm/fedora/rust-keylime-metadata.patch

Allow setting the path to the binary bios measurements log file via the `TPM_BINARY_MEASUREMENTS` environment variable when build with the `testing` feature enabled.
The binaries in the RPM are build with the `testing` feature enabled.
Fixes #490

Allow setting binary measured boot log path on RPM binaries

---

Cargo.lock
keylime-agent/Cargo.toml

Drop unused features from dependencies reducing the number of transitive dependencies and installation footprint.

Drop unused features from dependencies

---

rpm/fedora/rust-keylime-metadata.patch

With the changes in the Cargo.toml, the patch for the rpm also needs to
be fixed

rpm/fedora: Fix metadata patch

---

.packit.yaml
rpm/fedora/keylime-agent-rust.spec

Enable building RPM packages on Copr for all active Fedora versions
On Fedora-38 and current Rawhide, it is not possible to build the keylime agent due to the issues:
-  https://github.com/tpm2-software/tpm2-tools/issues/3210
- `tpm2-tools` is currently broken when build with `-lto -DFORTIFY_SOURCE=3`
- The `rust-base64` package version `0.13`, required to build `rust-tss-esapi` is not available.
This makes the RPM build to use vendored dependencies for all Fedora versions.

packit: Build RPM packages on Copr for fedora-all

---

Cargo.lock
keylime-agent/Cargo.toml
keylime-agent/src/crypto.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/quotes_handler.rs
keylime-agent/src/serialization.rs
keylime/Cargo.toml
keylime/src/tpm.rs

There were incompatible changes between version `0.13` and `0.21`, which requires some changes in the code.
Supersedes #570

Cargo: Update base64 to version 0.21

---

scripts/download_packit_coverage.sh

By not having hardcoded domain name in the regexp pattern we make adding different file hosting services easier.

[tests] Simply coverage file URL parsing

---

scripts/download_packit_coverage.sh

Recent tmt update modified a way how test directories are stored on a disk, adding "-XX" suffix to test
directory name in order to avoid conflicts in repetitive test execution. This patch accommodates 
the download script to this change.

[tests] Update test coverage task name regexp

---

docker/fedora/keylime_rust.Dockerfile

Obviously, the codes of the agent are located in the rust-keylime repository. However, there is no logic for cloning and compiling rust-keylime in the corresponding rust dockerfile. So we need to add it.
Fixes: #585 
Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>

docker/fedora/keylime_rust.Dockerfile: add the logic of cloning and compiling rust-keylime

---

keylime-agent/src/common.rs
keylime-agent/src/errors_handler.rs
keylime-agent/src/quotes_handler.rs

Fixes #589 
Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>

keylime-agent/src: update API version to 2.1 to consistent with https//github.com/keylime/keylime/blob/master/docs/rest_apis.rst

---

rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec

Remove ownership of /var/log/keylime which is unused.
Add Requires on util-linux-core for the mount command.

rpm: Remove unused directory and add dependency for mount

---

keylime-agent/src/common.rs
keylime-agent/src/secure_mount.rs

Remove MOUNT_SECURE bool and conditional
related with bool.Update secure mount
unit test to mount temp dir.

Remove MOUNT_SECURE bool

---

Cargo.lock

This fixes the compilation issue with the nightly compiler.
See:
* https://github.com/rust-lang/rust/issues/113152
* https://github.com/dtolnay/proc-macro2/pull/391
* https://github.com/rust-lang/rust/pull/111571

cargo: Bump proc-macro2 crate version

---

Cargo.lock
keylime-agent/Cargo.toml
keylime-agent/src/main.rs

Add support for shutting down on SIGTERM.
Resolves: #612

main: Gracefully shutdown on SIGTERM or SIGINT

---

keylime/src/tpm.rs

The current public key digest is using SHA1 and SHA256, and the digest will extend to TPM PCR 16. But from TPM2, SHA1 is not mandatory anymore, so this patch makes the hash algorithm configurable.
Reference:
TCG PC Client Platform TPM Profile Specification for TPM 2.0, Section 4.6 https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p05p_r14_pub.pdf

hash: add more configurable hash algorithm for public key digest

---

docker/release/Dockerfile.distroless
docker/release/Dockerfile.fedora
docker/release/Dockerfile.wolfi
docker/release/build_locally.sh

This PR aims to add a Dockerfile for a release version of the rust keylime agent.
**This is a work-in-progress at this point.** It is being discussed in the keylime-operator slack channel.
It currently contains a local build script like in the main keylime repository. Also, it contains different versions which have their advantages/disadvantages that we should discuss:
- `Dockerfile.distroless`:  an absolute bare minimum container which does not even have a shell. It is based on the "distroless" container effort from Google (which for example forms the base images for a couple of bigger projects like Kubernetes)
- `Dockerfile.wolfi`: also a bare minimum container which does not even have a shell. It is based on the wolfi container distribution from Chainguard which in turn was inspired by …

Adding release Dockerfiles

---

dist/systemd/system/keylime_agent.service
docker/release/Dockerfile.distroless
docker/release/Dockerfile.fedora
docker/release/Dockerfile.wolfi
keylime-ima-emulator/src/main.rs

This PR does the following things and is a follow-up on #613 and #601 :
- removes the `KillSignal=SIGINT` from the systemd service file as it can now safely rely on the SIGTERM default
- removes the `STOPSIGNAL SIGINT` from the Dockerfiles as it can also here now safely rely on the default SIGTERM being sent by container runtimes
- adds SIGTERM handling to the IMA emulator

Removing SIGINT stop signals from Dockerfiles and systemd service

---

.github/workflows/container.yml

Build the fedora-based image and push to quay.io

Build container image and push to quay.io

---

keylime-agent/src/main.rs

Use "currently" for swtpm emulator warning

---

docker/release/Dockerfile.distroless
docker/release/Dockerfile.fedora
docker/release/Dockerfile.wolfi

This allows dropping privileges inside the container.

docker: Add 'keylime' system user

---

.github/workflows/cargo-audit.yml
.github/workflows/rust.yml

Move the cargo-audit run from the static analysis job to a dedicated workflow using the github action instead of running the tool manually.
This improves the visibility of detected issues as the github action can use the checks interface and also create issues automatically.
The workflow runs cargo audit on pushes to master branch, when tags are created, or when a PR modifies dependencies (`Cargo.toml` or `Cargo.lock`)

Add workflow to run cargo-audit security audit

---

.github/workflows/cargo-audit.yml

use actions-rs/audit-check@v1 instead of actions-rs/audit-check@v1.4.1

Do not use too specific version on cargo audit workflow

---

keylime-agent.conf
keylime-agent/src/config.rs
keylime-agent/src/main.rs
keylime-agent/src/registrar_agent.rs
keylime-agent/src/serialization.rs
keylime/src/tpm.rs

This is the first of a series of PRs that will enable the use of IDevIDs and IAKs as proposed in enhancement 81.
The modifications to the Keylime repositories are:
**Keylime**
Columns for the IDevID and IAK are added to the database
The IAK and IDevID sent by the agent are processed
The AK is verified by the IAK
**Rust-Keylime**
Config options to enable IDevID and IAK generation and use are added, with choices on how to generate the IDevID and IAK
The IAK and IDevID are generated according to config options
The IAK is used to certify the AK in the registration process
The purpose of this PR is to begin enabling the use of IAK and IDevID in keylime, starting with their generation. Options for the server config are not yet added so the inclusion of IAK and IDevID are left as optional for …

Initial PR to add support for IDevID and IAK

---

keylime-agent/src/main.rs

Resolves: #652
According to The Rust RFC Book type privacy chapter: https://rust-lang.github.io/rfcs/2145-type-privacy.html "private_in_public" compatibility lint will be removed and its uses will be reported as warnings by
"renamed_and_removed_lints"

Remove private_in_public

---

tests/run.sh

This is a workaround for https://github.com/xd009642/tarpaulin/issues/1388
The issue was fixed upstream but not released yet, which makes our pipelines to fail.
This also adds the --engine llvm to try to solve the eventual timeout that happens on our tests.

tests: Fix tarpaulin issues with dropped -v option

---

Cargo.lock

cargo: Bump serde to version 1.0.188

---

keylime-agent.conf
keylime-agent/src/config.rs

The configuration version should've been bumped with the addition of the IDevID/IAK options, following the templates added for the configuration.
This also fixes the enable_iak_idevid processing as the option is a boolean which can be copied.

Bump configuration version and fix enable_iak_idevid

---

.github/workflows/submit-HEAD-coverage.yaml
packit-ci.fmf
scripts/download_packit_coverage.sh

Fedora 37 is EOL, use Fedora 39 instead

packit: Bump Fedora version used for code coverage

---

Cargo.toml
keylime-agent/Cargo.toml
keylime-ima-emulator/Cargo.toml
keylime/Cargo.toml

This allows us to define several crate dependencies in a single place: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table

Make use of workspace dependencies

---

keylime/src/tpm.rs

Add granular error types for every possible error raised by the `tpm` module. This improves diagnosing the cause of the errors without showing complex errors coming from underlying libraries.
This also drops all `expect()` and `unwrap()` uses to avoid panicking.
Fixes: #330, #639

tpm: Overhaul errors

---

.github/workflows/keylime-bot.yml

The workflow set the bot token in the environment, but did not pass it to the action as input.
This also removes the `LABEL` argument for the action, which was unused.

workflows: Fix keylime-bot token usage

---

Cargo.lock
Cargo.toml

This also bumps `picky-asn1-x509` to version `0.12.0` and `picky-asn1-der` to version `0.4.1`.
This update is important to allow the implementation of the support for ECC EK, which is currently not supported by the agent.

cargo: Bump tss-esapi to version 7.4.0

---

.github/workflows/container.yml
.github/workflows/rust.yml
.github/workflows/submit-HEAD-coverage.yaml
.github/workflows/submit-PR-coverage.yaml

This avoids warnings about deprecated node version on check runs

workflows: Update checkout action to version 4

---

GNUmakefile
keylime-agent.conf
keylime-agent/src/common.rs
keylime-agent/src/config.rs
keylime-agent/src/crypto.rs
keylime-agent/src/main.rs

As discussed in Issue #657  -- initial commit for implementing configurable logging paths

Adding "mutable log paths" feature 

---

Cargo.lock

This prevents error on `ahash` compilation with nightly `rustc`.
Note that the tests are expected to fail while https://github.com/RedHat-SP-Security/keylime-tests/pull/550 is not merged

cargo: Bump ahash to version 0.8.7

---

Cargo.lock
Cargo.toml
README.md
docker/fedora/keylime_rust.Dockerfile
docker/release/Dockerfile.distroless
docker/release/Dockerfile.fedora
docker/release/Dockerfile.wolfi
keylime-agent/Cargo.toml
keylime-agent/src/error.rs
keylime-agent/src/payloads.rs
rpm/centos/keylime-agent-rust.spec
rpm/fedora/keylime-agent-rust.spec
rpm/fedora/rust-keylime-metadata.patch

Replace `compress-tools` with `zip` crate
Remove mentions of `libarchive` dependency from `README`, as well as from rpm spec files and dockerfiles
Remove keylime user creation from non-fedora based dockerfiles.
Add wget installation to `wolfi` based image.
Fixes #733 
Fixes #671

cargo: Replace compress-tools with zip crate

---

keylime-agent.conf
keylime-agent/src/config.rs

This bug found during testing (of non-kubernetized keylime) by @niteeshkd. It was introduced by me in #665.

typo fix for default path to measured boot log file

---

keylime-agent/src/main.rs
keylime-agent/src/registrar_agent.rs
keylime/src/crypto.rs

Set X509 Subject Alternative Name with local  DNS names (localhost, localhost.domain) and  local IPs (127.0.0.1, ::1). It will also include the contact IP stored in configuration
Resolves: #327

Set X509 SAN with local DNSname/IP/IPv6

---

keylime/Cargo.toml

This feature enables tests that require a TPM and TCTI environment variable properly configured to run.

cargo: Add testing feature to keylime library

---

keylime-agent/src/config.rs
keylime-agent/src/error.rs
keylime-agent/src/main.rs
keylime-agent/src/registrar_agent.rs
keylime/src/crypto.rs
keylime/src/crypto/x509.rs
keylime/src/ip.pest
keylime/src/ip_parser.rs
keylime/src/lib.rs

This adds support for IPv6 addresses in the configuration with or without brackets.
The brackets are removed when the addresses are parsed and then added back when necessary.
This fixes the addition of IPv6 addresses in the mTLS certificate.
This also implements the builder pattern for the certificate generation.
Fixes: #583
Fixes: #753
Fixes: #755

config: Support IPv6 with or without brackets

---

keylime-agent.conf
keylime-agent/src/main.rs

This fixes [#760](https://github.com/keylime/rust-keylime/issues/760).
If a TPM has been set up with a non-string auth value, for example by running:
```tpm2_changeauth -c E "hex:0000DF0237BE41C0E0124CAAD0A619B29B8E3EE4173521656729C6F339DBC449"```
the keylime agent is not currently compatible with the TPM as there is no way provide this value.
This fixes the issue, by checking for "hex:" at the start of the tpm password and using a hex password if it is found.

Enable hex values to be used for tpm_ownerpassword

---

keylime/src/crypto.rs

The agent server used the `SslAcceptor::mozilla_intermediate()` which disables TLS 1.3 and restricts the TLS 1.2 ciphers to:
```
TLSv1.2:
ciphers:
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519)
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519)
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048)
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519)
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048)
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048)
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048)
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 2048) …
```

crypto: Enable TLS 1.3

---

rpm/centos/keylime-agent-rust.spec

Fix macro usage on centos-stream-10 build

rpm: fix COPR RPMs build for centos-stream-10

---

keylime/src/tpm.rs

This is a fix to change to Rsa 4096 for the IAK sha512 template. This is already the case for the IDevID template and the two should match.

fix IAK SHA512 template to match IDevID

---

keylime-agent/src/errors_handler.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs

Fix leftover 'unnecessary qualification' warnings generated when running the tests (`cargo test --features=testing`) with newer rust compilers.

Fix leftover 'unnecessary qualification' warnings on tests

---

keylime-agent/src/agent_handler.rs
keylime-agent/src/common.rs
keylime-agent/src/errors_handler.rs
keylime-agent/src/main.rs
packit-ci.fmf

This is a new read-only API on the agent to allow for 3rd party integrations (starting with SPIRE) that will need certain information about the agent.

Adding /agent/info API to agent

---

keylime-agent.conf
keylime-agent/src/config.rs
keylime-agent/src/main.rs
keylime/src/tpm.rs

This PR adds into the config the ability to specify handles and auth values for IDevID and IAK keys. The auth values function in the same way as the TPM ownerpassword in that they can be [hex values](https://github.com/keylime/rust-keylime/pull/769).
The new config options are:
```
idevid_password = ""
idevid_handle = ""
iak_password = ""
iak_handle = ""
```

Add the ability to use persistent handles for IDevID and IAK rather than regenerating, and add auth values for them

---

keylime-agent/src/config.rs
keylime-agent/src/error.rs
keylime-agent/src/registrar_agent.rs
keylime/src/hostname.pest
keylime/src/hostname_parser.rs
keylime/src/lib.rs

This restores previous behavior where hostnames could be used to set the 'registrar_ip' configuration option.
The configuration will try to parse the input configuration string as an IP and in case of failure, try to parse the string as a hostname.
Fixes: #794

config: Support hostnames in registrar_ip option

---

rpm/fedora/keylime-agent-rust.spec

Changes based on patch by Yaakov Selkowitz on Fedora
The rust macros in Fedora were updated. This fixes the specfile used to build on Fedora with the new macros

rpm/fedora: Update rust macro usage

---

keylime-agent/src/error.rs
keylime-agent/src/revocation.rs
keylime-agent/src/secure_mount.rs

Fix some warnings raised by clippy

Fix clippy warnings

---

keylime-agent/src/revocation.rs
keylime/src/crypto/x509.rs

These were reported by clippy as issues

keylime/crypto: Fix indentation of documentation comment

---

packit-ci.fmf

This is a test for IDevIDs and IAKs that are persisted in the TPM and are accessed via handle rather than regenerated. These keys may also be protected by password, this is also tested, as is the change to enable hex passwords for the TPM.

Enable test functional/iak-idevid-persisted-and-protected

---

packit-ci.fmf

Before running tests apply workarounds to known
distribution bugs so we reduce the amount of
test failures.

tests: apply workarounds to known bugs

---

keylime-agent/src/config.rs
keylime-agent/src/error.rs
keylime-agent/src/main.rs
keylime-agent/src/payloads.rs

Instead of using explicit dedicated transformations for each option in the configuration structure, use an intermediary JSON structure to implement the `collect()` method in a more generic way.
This makes it easier to add new configuration options and simplifies maintenance.
Also, instead of duplicating the `AgentConfig` structure to receive the options set in the environment variables, use the built-in `Environment` `Source` trait implementation with a small change to make it possible to use as a source for a `KeylimeConfig` structure.

config: Refactor `AgentConfig` `Source` trait implementation

---

keylime-agent/src/config.rs

In case of invalid UUID agent showed:
```
WARN  keylime_agent::config > Misformatted UUID: invalid-uuid-0909
INFO  keylime_agent::config > Using generated UUID: invalid-uuid-0909
```
and warning while compiling:
```
warning: unused import: `std::io::prelude`
--> keylime/src/tpm.rs:1816:9
|
1816 |     use std::io::prelude::*;
|         ^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```

Fix showing wrong UUID, remove unused library

---

GNUmakefile

Prepends ${DESTDIR} for config dir creation and config file copying, so its in line with the other artifacts. Makes no sense to be able to install to dir X but config files being created in the system /etc/ dir

Use ${DESTDIR} for config

---

keylime-agent/src/agent_handler.rs
keylime-agent/src/api.rs
keylime-agent/src/errors_handler.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/notifications_handler.rs
keylime-agent/src/quotes_handler.rs

Move the configuration of the API for each scope into the respective handler file.
Also, move the API configuration into a dedicated file, and make it modular.
This is a preparation to add support for multiple API versions.

Make the API configuration modular

---

packit-ci.fmf
scripts/download_packit_coverage.sh

Replace the Fedora 39 usage to generate code coverage with Fedora 41.
This is necessary because Fedora 39 is now EOL and the tests are not executed for it anymore.

tests: Use Fedora 41 to generate code coverage

---

.github/workflows/submit-HEAD-coverage.yaml

The coverage for merged PRs should be obtained from the Fedora 41 run.
This change was missing on the previous PR #873

workflows: Submit the coverage for merged PR from Fedora 41

---

keylime-agent/src/config.rs
keylime-agent/src/main.rs

For the options 'ip', 'contact_ip', and 'registrar_ip', allow a hostname to be used instead of an IP address.
Fixes #848

config: Enable passing a hostname instead of IP

---

Cargo.lock
keylime-agent/src/agent_handler.rs
keylime-agent/src/common.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/notifications_handler.rs
keylime-agent/src/quotes_handler.rs
keylime/Cargo.toml
keylime/src/tpm.rs
tests/run.sh
tests/setup_swtpm.sh

This implements a singleton to use a single instance of the
`tss_espi::Context`.
This also avoids race conditions by using a thread-safe mutex to access
the context.
The tests were modified to cleanup generated key handles between test
cases, preventing leftover handles to fill the TPM memory.
Introduce a mutex to allow only a single test that create keys in the
TPM to run at once.  It is required that tests that create keys in the
TPM to run the `tpm::testing::lock_tests()` to obtain the mutex and be
able to continue executing without the risk of other tests filling the
TPM memory.
The `QuoteData::fixture` implementation (used only during tests) was
modified to flush the created key contexts when dropped. It also was
modified to lock the global mutex by calling the …

Use a single TPM context and avoid race conditions during tests

---

tests/ca.conf
tests/generate-iak-idevid-certs.sh
tests/run.sh
tests/setup_swtpm.sh

The script generates a test root CA and intermediate CA keys and certificates. The output directory can be set via the `--output` option, and the CA password with the `--pwd` option.  If an output directory is not set, a temporary directory is created and the certificates are placed there.
Then, the script generates the IDevID and IAK keys inside the TPM and respective certificates.
The script requires the `tpm2-openssl` provider to access the keys inside the TPM.
It is recommended to setup the TCTI, TPM2TOOLS_TCTI, and TPM2OPENSSL_TCTI environment variables to select the TPM to use. If not set, the default `/dev/tpmrm0` will be used instead.
This also modifies the `tests/setup_swtpm.sh` and `tests/run.sh` to configure the TPM2OPENSSL_TCTI to use the `swtpm` with the `tpm2-openssl` …

tests: Add script to generate IAK and IDevID certificates

---

.packit.yaml

The `cargo-vendor-filterer` will drop dependencies addded by disabled features. Add the `--all-features` option to keep the dependencies added by all features in the generated vendor directory.
Without this, the RPM builds on COPR are currently failing. The RPMs used for testing are currently outdated and don't contain the changes related with the multiple API version support

packit: Fix RPM builds on copr

---

Cargo.lock
Cargo.toml

Bump `base64` crate to version `0.22.1`

cargo: Bump base64 crate to version 0.22.1

---

Cargo.lock
Cargo.toml

Update `clap` crate to version `4.5.23`

cargo: Bump clap crate to version 4.5.23

---

scripts/download_packit_coverage.sh

This fixes the currently failing coverage report job on CI.
The regex did not accept `http://` but only `https://` URLs. This makes the regex more flexible allowing us to use the current archive storage which provides only `http://`.

scripts: Fix regex in download_packit_coverage.sh

---

keylime-agent/src/main.rs

This fixes a waning on newer rust compilers that complains about it.

main: Remove unnecessary lifetime

---

scripts/download_packit_coverage.sh

Instead of using an intermediary files storage service, download the file directly from the Testing Farm artifacts storage.

scripts: Download coverage data from Testing Farm directly

---

dist/systemd/system/keylime_agent.service

Set the logging level as `INFO` for the `keylime` library in the systemd service file.
Some of the messages were moved from main to the library and would not be logged without this setting.

dist: Enable logging for keylime library in the service

---

scripts/download_packit_coverage.sh

Fix `COVERAGE_DIR` parsing from results by using the `-m 1` option in `grep` command to limit the output to a single match.

scripts: Fix coverage information downloading script

---

keylime-agent/src/main.rs

Currently, `keylime_agent` must be started as root, and then drops permissions later.
This is not strictly necessary, as long as the agent has permission to talk to the TPM and read the TPM/IMA logs (e.g. through a group and/or ACLs).
This PR changes the UID check on startup to allow starting without root privileges.
If `run_as` is configured but we are already running unprivileged, then the `run_as` option will be ignored with a warning.
This allows, for example, running `keylime_agent` from a systemd service with `DynamicUsers=true`.

Allow agent to start without root privileges

---

packit-ci.fmf

The test tries all API versions supported by the agent against the latest server components.

packit: Add compatibility/api_version_compatibility test

---

keylime/src/lib.rs
keylime/src/structures/capabilities_negotiation.rs
keylime/src/structures/mod.rs

This change aims to include those structures
that will be required to communicate
capabilities negotiation information for
Keylime Push model
Resolves: #933 
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

Add capabilities_negotiation structures

---

keylime-agent.conf

The other algorithms, while supported by the TPM, are not supported on the Keylime verifier side.

keylime-agent.conf: only mention ecdsa and rsassa for signing

---

keylime-agent/src/agent_registration.rs
keylime-agent/src/main.rs

Add agent_registration.rs to include all code
relevant to this kind of operation
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

Code refactoring: Include AgentIdentity

---

keylime-agent/src/common.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/payloads.rs
keylime/src/crypto.rs
keylime/src/crypto/symmkey.rs

Move the SymmKey structure from `common.rs` into the keylime library (`crypto::symmkey`).
This is to continue the effort to move the code that can be shared from the `keylime-agent` application to the `keylime` library

Move SymmKey from common to the keylime library

---

keylime-agent/src/common.rs
keylime-agent/src/keys_handler.rs
keylime-agent/src/payloads.rs
keylime/src/crypto.rs
keylime/src/crypto/auth_tag.rs
keylime/src/crypto/encrypted_data.rs

Move the EncryptedData and AuthTag structures from common.rs into the keylime library.
This is to continue the effort to move the code that can be shared from the keylime-agent application to the keylime library

Move AuthTag and EncryptedData from the common.rs to the Keylime library

---

keylime/src/structures/evidence_handling.rs
keylime/src/structures/mod.rs

Define EvidenceHandling structures

---

Cargo.lock
Cargo.toml
keylime-agent.conf
keylime-agent/src/agent_handler.rs
keylime-agent/src/common.rs
keylime-agent/src/config.rs
keylime-agent/src/main.rs
keylime-push-model-agent/src/registration.rs
keylime/src/algorithms.rs
keylime/src/tpm.rs

This implements a selection of the different key sizes for RSA and curves for ECC for EK and AK using the backported changes in rust-tss-esapi. 
Further this then also enables us to use EK certs for non default key types.
Note this is currently blocked until https://github.com/parallaxsecond/rust-tss-esapi/pull/546 gets merged and we have a new release.

Enable different key sizes and curves for EK and AK

---

.gitignore
keylime/src/agent_identity.rs
keylime/src/agent_registration.rs
keylime/src/keylime_error.rs
keylime/src/lib.rs
keylime/src/registrar_client.rs

Introduce a new `AgentIdentity` structure that contains the Agent identity information, removing the corresponding data from the `RegistrarClient` structure.

Move Agent identity information from the `RegistrarClient` structure to the new structure AgentIdentity

---

Cargo.lock
Cargo.toml
keylime-push-model-agent/src/struct_filler.rs
keylime/Cargo.toml
keylime/src/cert.rs
keylime/src/config/push_model.rs
keylime/src/error.rs
keylime/src/lib.rs
keylime/src/uefi/mod.rs
keylime/src/uefi/uefi_log_handler.rs

Add UEFI log handler, use it to send UEFI count

---

keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/registration.rs
keylime-push-model-agent/src/struct_filler.rs
keylime/src/config/base.rs
keylime/src/config/push_model.rs
keylime/src/context_info.rs

This change introduces a new configuration option, disabled_signing_algorithms, to prevent the agent from using certain signing schemes, even if they are reported as supported by the TPM.
The primary motivation is to avoid issues with the `ecschnorr` algorithm, which, while technically supported by some TPMs, has been observed to cause rejection from Verifier.

Add disallowed_signing_algorithms, avoid ecschnorr

---

keylime/src/uefi/uefi_log_handler.rs

This change makes the UEFI test more robust by improving how it checks for the UEFI log file.
The original code used std::path::Path::new(log_path).exists(). This check is insufficient because it only verifies that the file path exists. It does not check if the program has the necessary permissions to read the file.
In a testing environment, the file might exist but be unreadable by the user running the test (e.g., it requires root privileges). This would cause the .exists() check to pass, but the subsequent line, UefiLogHandler::new(log_path).expect(...), would fail and cause the test to panic.
The code is changed to std::fs::File::open(log_path).is_ok(). This single line of code attempts to open the file for reading and checks if the operation was successful.
This is superior because it …

Fix UEFI test to check file access in all cases

---

keylime/src/structures/capabilities_negotiation.rs

This change enhances the capabilities negotiation phase of the push-attestation protocol by adding two timestamp fields to the verifier's response: capabilities_received_at and challenges_expire_at.
This change aligns the Rust data structures with the complete protocol specification, allowing the agent to correctly deserialize and process the time-sensitive information sent by the verifier.
ResponseAttributes Struct Updated: The ResponseAttributes struct in keylime/src/structures/capabilities_negotiation.rs has been modified to include two new optional fields:
* capabilities_received_at: Option<DateTime<Utc>>: Records the exact time when the verifier processed the agent's initial capabilities request, establishing a baseline for the session.
* challenges_expire_at: Option<DateTime<Utc>>: …

Add Capabilities Negotiations resp. missing fields

---

keylime/src/structures/evidence_handling.rs

This commit adds an additional unit test to evidence_handling.rs, named deserialize_evidence_handling_request_invalid_entry_count_format to verify that the agent correctly rejects evidence payloads with a logically invalid entry_count. Specifically, it ensures that a negative value for entry_count is properly handled as an error during deserialization.
* Test Case: The new test defines a JSON payload for an EvidenceHandlingRequest. Inside an ima_log evidence block, the entry_count field is intentionally set to -1.
* Expected Behavior: The test asserts that attempting to deserialize this JSON into the Rust structs must fail. This is because the corresponding struct field is defined as a usize (an unsigned integer), which cannot represent a negative number.
* Validation: The test confirms …

Increase coverage in evidence handling structure

---

Cargo.lock
Cargo.toml
keylime-push-model-agent/Cargo.toml
keylime-push-model-agent/src/attestation.rs
keylime-push-model-agent/src/main.rs
keylime/Cargo.toml
keylime/src/config/base.rs
keylime/src/config/push_model.rs
keylime/src/lib.rs
keylime/src/resilient_client.rs

This pull request introduces a resilient HTTP client with an exponential backoff strategy to enhance the robustness of the Keylime push model agent. This new client is then integrated into the push-model agent's attestation process, making it more tolerant of transient network failures and temporary server-side errors.
1. Add Resilient HTTP Client with Exponential Backoff
The first commit adds a new, reusable module named resilient_client.
* New Module: Creates keylime/src/resilient_client.rs.
* Functionality: This module provides a ResilientClient that wraps reqwest. It uses the reqwest-retry and reqwest-middleware crates to automatically retry failed HTTP requests.
* Custom Retry Strategy: A custom retry strategy, StopOnSuccessStrategy, is implemented. This allows the client to …

Add resilient_client for exponential backoff

---

keylime-push-model-agent/src/struct_filler.rs
keylime/src/context_info.rs
keylime/src/structures/capabilities_negotiation.rs
keylime/src/structures/evidence_handling.rs
keylime/src/tpm.rs

The signing scheme and hash algorithm that the AK can use is set and locked during its generation.  This means that an AK cannot be used to generate signatures using a different scheme.
This adds a method to extract the signing scheme and hash algorithm set during the AK generation from the TPM for the given AK.
The push attestation agent prototype is modified to generate a quote using the extracted signing scheme and hash algorithm.

tpm: Add method to extract signing scheme and hash algorithm from AK

---

keylime-push-model-agent/src/attestation.rs
keylime/src/registrar_client.rs
keylime/src/resilient_client.rs

This patch refactors the resilient_client to fix a JSON double-encoding bug that caused the verifier to reject requests.
The root cause of the "malformed parameters" error from Verifier was that the `get_json_request` function was being called with a String that already contained JSON. The function would then re-serialize this string, wrapping it in an extra layer of quotes and escaping its contents, leading to a double-encoded payload.
This PR resolves the issue by improving the client's API to be more explicit and prevent this error by design.
* keylime/src/resilient_client.rs:
The original `get_json_request` function has been refactored. Its signature is changed to accept a pre-serialized string slice (json_string: &str) and it now uses this string directly as the request body without …

Fix body sending by allowing serializing strings 

---

keylime-push-model-agent/src/attestation.rs
keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/state_machine.rs
keylime-push-model-agent/src/url_selector.rs

This commit refactors the main attestation logic into a state machine, simplifying the main function and making the agent's state 
The state machine handles the agent's lifecycle, from registration to attestation.

push-model: refactor attestation logic into a state machine

---

keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/registration.rs
keylime/src/config/base.rs
keylime/src/config/push_model.rs

The primary reason for this change is to improve code clarity and consistency. Using the full word `exponential_backoff` instead of the abbreviation expbackoff makes the configuration options easier to understand for new developers and aligns them with the naming conventions used elsewhere in the Keylime codebase. This change has no impact on functionality. To address this, renaming of three configuration variables is performed across the codebase to be more descriptive and consistent:
- `expbackoff_initial_delay` is now `exponential_backoff_initial_delay`
- `expbackoff_max_retries` is now `exponential_backoff_max_retries`
- `expbackoff_max_delay` is now `exponential_backoff_max_delay`
This renaming has been applied consistently in all the places where these parameters are defined or …

Align exp.backoff to current configuration format

---

keylime-push-model-agent/src/attestation.rs
keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/state_machine.rs

After the first successful attestation, the agent now waits for a
configurable interval before repeating the attestation process by
returning to the Negotiating state, creating a continuous attestation
loop.
The interval between the attestations is currently fixed, but in the
future, the verifier will provide this information in its response to
the attestation, so we can parse it from there and use it instead.
Currently, the interval between sending the measurements is defined
as 60s, but can be configured with the --attestation-interval-seconds
switch.

push-model: implement continuous attestation with configurable intervals

---

Cargo.lock
Cargo.toml

The `retry-policies` crate in Fedora uses the version 0.4.0

cargo: Bump retry-policies to version 0.4.0

---

keylime-push-model-agent/src/struct_filler.rs

This patch corrects the MIME type format for the IMA log reported by the agent.
The value for formats was changed from the incorrect "application/text" to the standard and correct "text/plain". This ensures the agent's capabilities report aligns with IANA standards and what the verifier expects for a plain text IMA log.

Fix IMA log format (it must be 'text/plain')

---

keylime-push-model-agent/src/struct_filler.rs
keylime/src/boot_time.rs
keylime/src/lib.rs

This patch correctly implements boot time retrieval for the Rust agent, replacing the temporary use of the current time with the actual system boot time.
* New boot_time.rs Module: A new module was created to contain the logic for getting the system boot time. It works by parsing the btime field from the /proc/stat file, which is the standard method on Linux.
* Updated Agent Payload: The agent no longer sends the current time (chrono::Utc::now()) as the boot_time. Instead, it now calls the new get_boot_time() function to provide the true boot time in its capabilities report.
* Error Handling: If reading the boot time fails, the agent now logs an error and defaults to the Unix epoch (1970-01-01), ensuring the program doesn't crash.

Fix boot time retrieval

---

keylime-push-model-agent/src/state_machine.rs

This patch refactors the agent's state machine to make it more resilient
by preventing it from exiting on recoverable attestation or negotiation
errors. Previously, any failure during these stages would transition the
agent to a terminal Failed state.
This change ensures that the agent can recover from transient issues
(like network hiccups or temporary verifier unavailability) without
needing to be restarted. This is the list of the key changes:
* New AttestationFailed State: A new, non-terminal state
AttestationFailed(error, context) has been introduced to specifically
handle recoverable errors that occur during communication with the
verifier.
* Retry Logic: The main run loop now handles the AttestationFailed
state. When this state is reached, the agent will:
* Log the error: Wait for …

Add state to avoid exiting on wrong attestation

---

Cargo.lock
keylime-push-model-agent/Cargo.toml
keylime-push-model-agent/src/auth.rs
keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/struct_filler.rs
keylime/src/structures/sessions.rs
keylime/src/tpm.rs

Add authentication module implementing the challenge-response protocol
from Keylime Enhancement 103 [1].
Provides the two-step auth flow with session token management, mock TPM
operations, and error handling.
[1] https://github.com/keylime/enhancements/blob/master/103_agent-driven-attestation.md#challengeresponse-protocol-for-agent-authentication

Add authentication module implementing the challenge-response protocol

---

keylime-agent/src/keys_handler.rs
keylime-agent/src/main.rs
keylime-agent/src/payloads.rs
keylime-agent/src/revocation.rs
keylime-push-model-agent/Cargo.toml
keylime-push-model-agent/src/context_info_handler.rs
keylime-push-model-agent/src/main.rs
keylime-push-model-agent/src/registration.rs
keylime-push-model-agent/src/state_machine.rs
keylime-push-model-agent/src/struct_filler.rs
keylime/src/agent_data.rs
keylime/src/config/base.rs
keylime/src/config/env.rs
keylime/src/config/error.rs
keylime/src/config/mod.rs
keylime/src/config/push_model.rs
keylime/src/config/singleton.rs
keylime/src/config/testing.rs
keylime/src/context_info.rs
keylime/tests/config_singleton_integration.rs

This makes use of the singleton pattern to avoid re-reading the configuration files multiple times. Also, by providing a global way to obtain a reference to the configuration options (via the `get_config()` method), there is no need to pass the configuration structure through multiple layers, simplifying the API.
The configuration is basically immutable after loaded and processed, which means that it is basically read-only throughout the execution of the agent. Since no changes are expected to the configuration options after it is first loaded, there is no need to protect it against concurrent accesses. Using only references to the configuration options instead of creating copies via `clone()` improves the performance and reduces the memory usage.
For testing, it is necessary to have a …

config: Use the singleton pattern to avoid reading the files multiple times

---

rpm/centos/rust-keylime-metadata.patch
rpm/fedora/rust-keylime-metadata.patch

Fix the patches used to build the RPM packages in Copr to apply to current code.

rpm: Fix patches to apply to current master code

---

rpm/centos/rust-keylime-metadata.patch
rpm/fedora/rust-keylime-metadata.patch

This also fixes the latest introduced build errors during the RPM package build on Copr.

rpm: Do not remove wiremock which is now available in Fedora

---

keylime-push-model-agent/src/state_machine.rs

This PR resolves a clippy::needless_lifetimes warning found in the create_test_config test helper function.
The explicit 'a lifetime annotation was unnecessary, as Rust's lifetime elision rules can correctly infer the lifetime of the input &str and the returned NegotiationConfig.
The function signature has been updated to remove the explicit lifetime, making the code more idiomatic.

FSM: Fix compilation warnings detected by clippy

---

packit-ci.fmf

Enables test `/functional/add-agent-with-malformed-ek-cert` in Packit CI.

CI: Enable test add-agent-with-malformed-ek-cert

---

.github/workflows/rpm.yml

The tests simply try to patch the current code with the patches for both Fedora and CentOS. This is a sanity check to prevent changes changes that would make the patches incompatible to be introduced without properly updating the patches.

workflows: Add test to check if RPM patches still apply

---

keylime/src/context_info.rs
keylime/src/structures/evidence_handling.rs

Update ImaLog and UefiLog structures to handle null entries field:
- Change entries field from String to Option<String> in both structures
- Update serialization/deserialization logic to handle null values
- Modify entry count calculation for ImaLog to handle None entries
- Add comprehensive tests for null entries scenarios
- Update context_info.rs to wrap entries in Some() when creating evidence
This change improves robustness when handling evidence data that may null entry fields, which can occur in certain attestation scenarios.

Accept evidence handling structures null entries

---

docker/release/Dockerfile.distroless

When building the keylime_agent docker image, the process fails with the following error:
```text
[...]
------
> [builder 12/14] RUN make RELEASE=1 TARGETDIR=target target/release/keylime_agent:
0.164 Package systemd was not found in the pkg-config search path. 0.164 Perhaps you should add the directory containing `systemd.pc' 0.164 to the PKG_CONFIG_PATH environment variable
0.164 No package 'systemd' found
0.164 cargo build --target-dir="target" --release
0.305 error: failed to parse lock file at: /src/rust-keylime/Cargo.lock 0.305
0.305 Caused by:
0.305   lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?
0.305 make: *** [GNUmakefile:27: target/release/keylime_agent] Error 101
------
Dockerfile.distroless:26 …
```

docker: update rust to 1.81 for distroless Dockerfile

---

keylime/src/algorithms.rs
keylime/src/context_info.rs

Update key_algorithm reporting in the certification_keys object to use simple specifiers ("rsa" or "ecc") instead of full algorithm names ("rsa2048", "ecc256", etc.) to comply with the push model protocol specification.
This is not an issue for algorithm identification because the certification_keys object also includes the key_size field, allowing complete identification of the exact algorithm in use.

Use simple algorithm specifiers in certification_keys object

---

keylime-agent.conf
keylime-agent/src/main.rs
keylime/src/config/base.rs
keylime/src/config/env.rs
keylime/src/config/testing.rs
keylime/src/crypto.rs

Previously, when the agent was restarted while being monitored by the verifier, it would fail attestation because the PCR#16 would be extended with the new ephemeral payload public key.
With this change, the payload key is persisted, making the agent to reuse the previously generated payload key instead of generating a new ephemeral key on restart.
Resolves: #1136

Persist the payload key to avoid failing attestation on restart
